//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Sonya5
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Банк.
    /// </summary>
    // *** Start programmer edit section *** (Банк CustomAttributes)

    // *** End programmer edit section *** (Банк CustomAttributes)
    public enum Банк
    {
        
        // *** Start programmer edit section *** (Банк.Тинькофф CustomAttributes)

        // *** End programmer edit section *** (Банк.Тинькофф CustomAttributes)
        Тинькофф,
        
        // *** Start programmer edit section *** (Банк.Сбербанк CustomAttributes)

        // *** End programmer edit section *** (Банк.Сбербанк CustomAttributes)
        Сбербанк,
        
        // *** Start programmer edit section *** (Банк.ВТБ CustomAttributes)

        // *** End programmer edit section *** (Банк.ВТБ CustomAttributes)
        ВТБ,
        
        // *** Start programmer edit section *** (Банк.АТБ CustomAttributes)

        // *** End programmer edit section *** (Банк.АТБ CustomAttributes)
        АТБ,
    }
}
