//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Sonya5
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Приход денег.
    /// </summary>
    // *** Start programmer edit section *** (ПриходДенег CustomAttributes)

    // *** End programmer edit section *** (ПриходДенег CustomAttributes)
    [AutoAltered()]
    [Caption("Приход денег")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПриходДенегE", new string[] {
            "ID as \'ID\'",
            "Дата as \'Дата\'",
            "ТипПрихода as \'Тип прихода\'",
            "Сумма as \'Сумма\'"})]
    [AssociatedDetailViewAttribute("ПриходДенегE", "СоставУслуги", "СоставУслугиE", true, "", "Состав услуги", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("ПриходДенегE", "СоставТовары", "СоставТоварыE", true, "", "Состав товары", true, new string[] {
            ""})]
    [View("ПриходДенегL", new string[] {
            "ID as \'ID\'",
            "Дата as \'Дата\'",
            "ТипПрихода as \'Тип прихода\'",
            "Сумма as \'Сумма\'"})]
    public class ПриходДенег : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private System.DateTime fДата;
        
        private IIS.Sonya5.ТипПрихода fТипПрихода;
        
        private int fСумма;
        
        private IIS.Sonya5.Клиенты fКлиенты;
        
        private IIS.Sonya5.DetailArrayOfСоставТовары fСоставТовары;
        
        private IIS.Sonya5.DetailArrayOfСоставУслуги fСоставУслуги;
        
        // *** Start programmer edit section *** (ПриходДенег CustomMembers)

        // *** End programmer edit section *** (ПриходДенег CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (ПриходДенег.ID CustomAttributes)

        // *** End programmer edit section *** (ПриходДенег.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (ПриходДенег.ID Get start)

                // *** End programmer edit section *** (ПриходДенег.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (ПриходДенег.ID Get end)

                // *** End programmer edit section *** (ПриходДенег.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриходДенег.ID Set start)

                // *** End programmer edit section *** (ПриходДенег.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (ПриходДенег.ID Set end)

                // *** End programmer edit section *** (ПриходДенег.ID Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ПриходДенег.Дата CustomAttributes)

        // *** End programmer edit section *** (ПриходДенег.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ПриходДенег.Дата Get start)

                // *** End programmer edit section *** (ПриходДенег.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ПриходДенег.Дата Get end)

                // *** End programmer edit section *** (ПриходДенег.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриходДенег.Дата Set start)

                // *** End programmer edit section *** (ПриходДенег.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ПриходДенег.Дата Set end)

                // *** End programmer edit section *** (ПриходДенег.Дата Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (ПриходДенег.Сумма CustomAttributes)

        // *** End programmer edit section *** (ПриходДенег.Сумма CustomAttributes)
        public virtual int Сумма
        {
            get
            {
                // *** Start programmer edit section *** (ПриходДенег.Сумма Get start)

                // *** End programmer edit section *** (ПриходДенег.Сумма Get start)
                int result = this.fСумма;
                // *** Start programmer edit section *** (ПриходДенег.Сумма Get end)

                // *** End programmer edit section *** (ПриходДенег.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриходДенег.Сумма Set start)

                // *** End programmer edit section *** (ПриходДенег.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (ПриходДенег.Сумма Set end)

                // *** End programmer edit section *** (ПриходДенег.Сумма Set end)
            }
        }
        
        /// <summary>
        /// ТипПрихода.
        /// </summary>
        // *** Start programmer edit section *** (ПриходДенег.ТипПрихода CustomAttributes)

        // *** End programmer edit section *** (ПриходДенег.ТипПрихода CustomAttributes)
        public virtual IIS.Sonya5.ТипПрихода ТипПрихода
        {
            get
            {
                // *** Start programmer edit section *** (ПриходДенег.ТипПрихода Get start)

                // *** End programmer edit section *** (ПриходДенег.ТипПрихода Get start)
                IIS.Sonya5.ТипПрихода result = this.fТипПрихода;
                // *** Start programmer edit section *** (ПриходДенег.ТипПрихода Get end)

                // *** End programmer edit section *** (ПриходДенег.ТипПрихода Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриходДенег.ТипПрихода Set start)

                // *** End programmer edit section *** (ПриходДенег.ТипПрихода Set start)
                this.fТипПрихода = value;
                // *** Start programmer edit section *** (ПриходДенег.ТипПрихода Set end)

                // *** End programmer edit section *** (ПриходДенег.ТипПрихода Set end)
            }
        }
        
        /// <summary>
        /// Приход денег.
        /// </summary>
        // *** Start programmer edit section *** (ПриходДенег.Клиенты CustomAttributes)

        // *** End programmer edit section *** (ПриходДенег.Клиенты CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиенты"})]
        [NotNull()]
        public virtual IIS.Sonya5.Клиенты Клиенты
        {
            get
            {
                // *** Start programmer edit section *** (ПриходДенег.Клиенты Get start)

                // *** End programmer edit section *** (ПриходДенег.Клиенты Get start)
                IIS.Sonya5.Клиенты result = this.fКлиенты;
                // *** Start programmer edit section *** (ПриходДенег.Клиенты Get end)

                // *** End programmer edit section *** (ПриходДенег.Клиенты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриходДенег.Клиенты Set start)

                // *** End programmer edit section *** (ПриходДенег.Клиенты Set start)
                this.fКлиенты = value;
                // *** Start programmer edit section *** (ПриходДенег.Клиенты Set end)

                // *** End programmer edit section *** (ПриходДенег.Клиенты Set end)
            }
        }
        
        /// <summary>
        /// Приход денег.
        /// </summary>
        // *** Start programmer edit section *** (ПриходДенег.СоставТовары CustomAttributes)

        // *** End programmer edit section *** (ПриходДенег.СоставТовары CustomAttributes)
        public virtual IIS.Sonya5.DetailArrayOfСоставТовары СоставТовары
        {
            get
            {
                // *** Start programmer edit section *** (ПриходДенег.СоставТовары Get start)

                // *** End programmer edit section *** (ПриходДенег.СоставТовары Get start)
                if ((this.fСоставТовары == null))
                {
                    this.fСоставТовары = new IIS.Sonya5.DetailArrayOfСоставТовары(this);
                }
                IIS.Sonya5.DetailArrayOfСоставТовары result = this.fСоставТовары;
                // *** Start programmer edit section *** (ПриходДенег.СоставТовары Get end)

                // *** End programmer edit section *** (ПриходДенег.СоставТовары Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриходДенег.СоставТовары Set start)

                // *** End programmer edit section *** (ПриходДенег.СоставТовары Set start)
                this.fСоставТовары = value;
                // *** Start programmer edit section *** (ПриходДенег.СоставТовары Set end)

                // *** End programmer edit section *** (ПриходДенег.СоставТовары Set end)
            }
        }
        
        /// <summary>
        /// Приход денег.
        /// </summary>
        // *** Start programmer edit section *** (ПриходДенег.СоставУслуги CustomAttributes)

        // *** End programmer edit section *** (ПриходДенег.СоставУслуги CustomAttributes)
        public virtual IIS.Sonya5.DetailArrayOfСоставУслуги СоставУслуги
        {
            get
            {
                // *** Start programmer edit section *** (ПриходДенег.СоставУслуги Get start)

                // *** End programmer edit section *** (ПриходДенег.СоставУслуги Get start)
                if ((this.fСоставУслуги == null))
                {
                    this.fСоставУслуги = new IIS.Sonya5.DetailArrayOfСоставУслуги(this);
                }
                IIS.Sonya5.DetailArrayOfСоставУслуги result = this.fСоставУслуги;
                // *** Start programmer edit section *** (ПриходДенег.СоставУслуги Get end)

                // *** End programmer edit section *** (ПриходДенег.СоставУслуги Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриходДенег.СоставУслуги Set start)

                // *** End programmer edit section *** (ПриходДенег.СоставУслуги Set start)
                this.fСоставУслуги = value;
                // *** Start programmer edit section *** (ПриходДенег.СоставУслуги Set end)

                // *** End programmer edit section *** (ПриходДенег.СоставУслуги Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПриходДенегE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПриходДенегE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПриходДенегE", typeof(IIS.Sonya5.ПриходДенег));
                }
            }
            
            /// <summary>
            /// "ПриходДенегL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПриходДенегL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПриходДенегL", typeof(IIS.Sonya5.ПриходДенег));
                }
            }
        }
    }
}
