//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Sonya5
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Регистр.
    /// </summary>
    // *** Start programmer edit section *** (Регистр CustomAttributes)

    // *** End programmer edit section *** (Регистр CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РегистрE", new string[] {
            "ID as \'ID\'"})]
    [View("РегистрL", new string[] {
            "ID as \'ID\'"})]
    public class Регистр : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private IIS.Sonya5.ПриходДенег fПриходДенег;
        
        private IIS.Sonya5.РасходДенег fРасходДенег;
        
        // *** Start programmer edit section *** (Регистр CustomMembers)

        // *** End programmer edit section *** (Регистр CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Регистр.ID CustomAttributes)

        // *** End programmer edit section *** (Регистр.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Регистр.ID Get start)

                // *** End programmer edit section *** (Регистр.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Регистр.ID Get end)

                // *** End programmer edit section *** (Регистр.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Регистр.ID Set start)

                // *** End programmer edit section *** (Регистр.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Регистр.ID Set end)

                // *** End programmer edit section *** (Регистр.ID Set end)
            }
        }
        
        /// <summary>
        /// Регистр.
        /// </summary>
        // *** Start programmer edit section *** (Регистр.ПриходДенег CustomAttributes)

        // *** End programmer edit section *** (Регистр.ПриходДенег CustomAttributes)
        [PropertyStorage(new string[] {
                "ПриходДенег"})]
        [NotNull()]
        public virtual IIS.Sonya5.ПриходДенег ПриходДенег
        {
            get
            {
                // *** Start programmer edit section *** (Регистр.ПриходДенег Get start)

                // *** End programmer edit section *** (Регистр.ПриходДенег Get start)
                IIS.Sonya5.ПриходДенег result = this.fПриходДенег;
                // *** Start programmer edit section *** (Регистр.ПриходДенег Get end)

                // *** End programmer edit section *** (Регистр.ПриходДенег Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Регистр.ПриходДенег Set start)

                // *** End programmer edit section *** (Регистр.ПриходДенег Set start)
                this.fПриходДенег = value;
                // *** Start programmer edit section *** (Регистр.ПриходДенег Set end)

                // *** End programmer edit section *** (Регистр.ПриходДенег Set end)
            }
        }
        
        /// <summary>
        /// Регистр.
        /// </summary>
        // *** Start programmer edit section *** (Регистр.РасходДенег CustomAttributes)

        // *** End programmer edit section *** (Регистр.РасходДенег CustomAttributes)
        [PropertyStorage(new string[] {
                "РасходДенег"})]
        [NotNull()]
        public virtual IIS.Sonya5.РасходДенег РасходДенег
        {
            get
            {
                // *** Start programmer edit section *** (Регистр.РасходДенег Get start)

                // *** End programmer edit section *** (Регистр.РасходДенег Get start)
                IIS.Sonya5.РасходДенег result = this.fРасходДенег;
                // *** Start programmer edit section *** (Регистр.РасходДенег Get end)

                // *** End programmer edit section *** (Регистр.РасходДенег Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Регистр.РасходДенег Set start)

                // *** End programmer edit section *** (Регистр.РасходДенег Set start)
                this.fРасходДенег = value;
                // *** Start programmer edit section *** (Регистр.РасходДенег Set end)

                // *** End programmer edit section *** (Регистр.РасходДенег Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РегистрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегистрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегистрE", typeof(IIS.Sonya5.Регистр));
                }
            }
            
            /// <summary>
            /// "РегистрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегистрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегистрL", typeof(IIS.Sonya5.Регистр));
                }
            }
        }
    }
}
