//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Sonya5
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состав товары.
    /// </summary>
    // *** Start programmer edit section *** (СоставТовары CustomAttributes)

    // *** End programmer edit section *** (СоставТовары CustomAttributes)
    [AutoAltered()]
    [Caption("Состав товары")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СоставТоварыE", new string[] {
            "Количество as \'Количество\'"})]
    public class СоставТовары : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private IIS.Sonya5.Товары fТовары;
        
        private IIS.Sonya5.ПриходДенег fПриходДенег;
        
        // *** Start programmer edit section *** (СоставТовары CustomMembers)

        // *** End programmer edit section *** (СоставТовары CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (СоставТовары.Количество CustomAttributes)

        // *** End programmer edit section *** (СоставТовары.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (СоставТовары.Количество Get start)

                // *** End programmer edit section *** (СоставТовары.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (СоставТовары.Количество Get end)

                // *** End programmer edit section *** (СоставТовары.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставТовары.Количество Set start)

                // *** End programmer edit section *** (СоставТовары.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (СоставТовары.Количество Set end)

                // *** End programmer edit section *** (СоставТовары.Количество Set end)
            }
        }
        
        /// <summary>
        /// Состав товары.
        /// </summary>
        // *** Start programmer edit section *** (СоставТовары.Товары CustomAttributes)

        // *** End programmer edit section *** (СоставТовары.Товары CustomAttributes)
        [PropertyStorage(new string[] {
                "Товары"})]
        [NotNull()]
        public virtual IIS.Sonya5.Товары Товары
        {
            get
            {
                // *** Start programmer edit section *** (СоставТовары.Товары Get start)

                // *** End programmer edit section *** (СоставТовары.Товары Get start)
                IIS.Sonya5.Товары result = this.fТовары;
                // *** Start programmer edit section *** (СоставТовары.Товары Get end)

                // *** End programmer edit section *** (СоставТовары.Товары Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставТовары.Товары Set start)

                // *** End programmer edit section *** (СоставТовары.Товары Set start)
                this.fТовары = value;
                // *** Start programmer edit section *** (СоставТовары.Товары Set end)

                // *** End programmer edit section *** (СоставТовары.Товары Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Sonya5.ПриходДенег.
        /// </summary>
        // *** Start programmer edit section *** (СоставТовары.ПриходДенег CustomAttributes)

        // *** End programmer edit section *** (СоставТовары.ПриходДенег CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ПриходДенег"})]
        public virtual IIS.Sonya5.ПриходДенег ПриходДенег
        {
            get
            {
                // *** Start programmer edit section *** (СоставТовары.ПриходДенег Get start)

                // *** End programmer edit section *** (СоставТовары.ПриходДенег Get start)
                IIS.Sonya5.ПриходДенег result = this.fПриходДенег;
                // *** Start programmer edit section *** (СоставТовары.ПриходДенег Get end)

                // *** End programmer edit section *** (СоставТовары.ПриходДенег Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставТовары.ПриходДенег Set start)

                // *** End programmer edit section *** (СоставТовары.ПриходДенег Set start)
                this.fПриходДенег = value;
                // *** Start programmer edit section *** (СоставТовары.ПриходДенег Set end)

                // *** End programmer edit section *** (СоставТовары.ПриходДенег Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СоставТоварыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СоставТоварыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СоставТоварыE", typeof(IIS.Sonya5.СоставТовары));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of СоставТовары.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСоставТовары CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСоставТовары CustomAttributes)
    public class DetailArrayOfСоставТовары : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Sonya5.DetailArrayOfСоставТовары members)

        // *** End programmer edit section *** (IIS.Sonya5.DetailArrayOfСоставТовары members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type СоставТовары by index.
        /// </summary>
        /// <summary>
        /// Adds object with type СоставТовары.
        /// </summary>
        public DetailArrayOfСоставТовары(IIS.Sonya5.ПриходДенег fПриходДенег) : 
                base(typeof(СоставТовары), ((ICSSoft.STORMNET.DataObject)(fПриходДенег)))
        {
        }
        
        public IIS.Sonya5.СоставТовары this[int index]
        {
            get
            {
                return ((IIS.Sonya5.СоставТовары)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Sonya5.СоставТовары dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
